In [1]:
import pandas as pd

df = pd.read_excel("../data/raw/synthetic_data.xlsx")

df.head()

           x           y
0  37.454012  104.070265
1  95.071431  246.183540
2  73.199394  193.457289
3  59.865848  149.726776
4  15.601864   47.906301

In [2]:
df.shape

(100, 2)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       100 non-null    float64
 1   y       100 non-null    float64
dtypes: float64(2)
memory usage: 1.7 KB

In [4]:
df.describe()

                x           y
count  100.000000  100.000000
mean    47.018074  127.539784
std     29.748941   73.826541
min      0.552212   13.990237
25%     19.320076   60.071983
50%     46.414245  124.748349
75%     73.020312  197.106120
max     98.688694  260.630849

In [5]:
df_v2 = df.copy()

df_v2.loc[len(df_v2)] = [50, 135]

df_v2.shape

(101, 2)

In [6]:
df_v2.to_excel("../data/raw/synthetic_data.xlsx", index=False)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import mlflow

ModuleNotFoundError: No module named 'mlflow'

In [10]:
import pandas as pd

file = "../data/raw/synthetic_data.xlsx"

df = pd.read_excel(file)

new_row = pd.DataFrame({
    "x": [70],
    "y": [184]
})

df = pd.concat([df, new_row], ignore_index=True)

df_v3 = df.to_excel(file, index=False)

print("Nouvelle ligne ajoutée.")
print("Shape :", df.shape)
print(df.tail())

Nouvelle ligne ajoutée.
Shape : (108, 2)
        x      y
103  60.0  160.0
104  80.0  209.0
105  90.0  234.0
106  70.0  184.0
107  70.0  184.0

In [12]:
df_v3.to_excel("../data/raw/synthetic_data.xlsx", index=False)

AttributeError: 'NoneType' object has no attribute 'to_excel'